### ISSUE TITLE
How to build the adjacent matrix?

### ISSUE THREAD

**Issue by iwtw** [JudyYe/zero-shot-gcn#10]
As the paper says that  "As for knowledge graph, we use the sub-graph of the WordNet [32], which includes around 30K object nodes." 
As I know that Wordnet provides the shortest path distance between two words, but how to build the adjacent matrix for Imagenet labels from Wordnet? The building process is mentioned for NELL and NEIL in the paper in details, could you please explain the process for Imagenet and Wordnet as well?

**Comment by iamkissg** [comment]
Hi @iwtw ,

In my opinion, you could simply choose a `threshold`  for the task. If the shortest path distance between two words is shorter than the chosen threshold, make a connection between the corresponded nodes. (There are different kinds of similarities besides the shortest path, which you could consider to use)

**Comment by fungtion** [comment]
@iamkissg I built the adjacent matrix using cosine distance, and with a threshold I make some values be 1 and others 0, then I l2 normalized this matrix, but the results keep the same and never improve during training, Is there something wrong? Thanks in advance.

**Comment by fungtion** [comment]
@iwtw the same problem, I obtain some adjacent matrixs from wordnet,  by setting the threshold of the shortest path distance to some values, but the performance of gcn is not better than fully-connected layer on my custom dataset.

**Comment by JudyYe** [comment]
We use http://www.image-net.org/archive/wordnet.is_a.txt provided by [ImageNet](http://image-net.org/download-API) instead of directly building tree from wordnet. 
These [folks](https://arxiv.org/abs/1805.11724) provided some insight into how the graph structure affects the performance
