### ISSUE TITLE
difference between semi-supervised learning and zero shot learning

### ISSUE THREAD

**Issue by 3DMM-ICME2023** [JudyYe/zero-shot-gcn#11]
Thanks for your nice work! @xiaolonw @JudyYe 
The GCN are first used for the  semi-supervised learning. In your work, GCN are adopted to solve the zero-shot learning. I think both problems are very similiar, such as some samples have not the label. Could you please tell me the difference between semi-supervised learning and zero shot learning?
Thank you in advance!

**Comment by kaiqiangh** [comment]
zero-shot learning refers to the categories can be classified without seeing any examples in training  step.
