### ISSUE TITLE
If gcn and knowledge graph powerful on traditional or one-shot classification problems?

### ISSUE THREAD

**Issue by lseiyjg** [JudyYe/zero-shot-gcn#16]
I have found some papers on classification with gcn and knowledge graph. But most papers focus on zero-shot problems. If this method effective on these one-shot or traditional cases?

**Comment by JudyYe** [comment]
Not sure what traditional cases you refer to.
As for few-shot learning, I'm not an expert. Zero-shot and few-shot are essentially different problems. 
Some recent work might be helpful: https://arxiv.org/abs/1911.09579.
And entry for general few-shot topic: 
- Snell, Jake, et. al "Prototypical Networks for Few-shot Learning." Neurips 2017.
- Wang, Yu-Xiong, et al. "Low-shot learning from imaginary data." CVPR 2018.

In this paper, we essentially say that category feature should be smooth in the visual classifier space defined by the graph.
