### ISSUE TITLE
Sharing extracted features

### ISSUE THREAD

**Issue by D-X-Y** [JudyYe/zero-shot-gcn#17]
Hi, thanks for this nice repo. Would you mind to share the extracted features, which are mentioned at here https://github.com/JudyYe/zero-shot-gcn/blob/master/DATASET.md#download-images-of-unseen-class-from-imagenet? Because imagenet images are currently not available (http://image-net.org/download-images), we can not obtain the original images.
```
Note: ImageNet is under maintenance. Original images outside ILSVRC are temporarily unavailable.
```

**Comment by JudyYe** [comment]
Sorry but I did not save one copy locally. #14
