### ISSUE TITLE
When downloading the data, there is a warning

### ISSUE THREAD

**Issue by joanconquerlee** [JudyYe/zero-shot-gcn#18]
I have regisered ImageNet using my school email and got the permission. But when I run: 
python tools/download_image.py --user myaccount --key accountpassword --save_dir ../images/ --hop 2  &
I got a list of  warnings:
does not have class ***. Do you forgot to download the picture??

**Comment by joanconquerlee** [comment]
I have fixed it

**Comment by Hanzy1996** [comment]
I have the same question. How to fix it?
