### ISSUE TITLE
img-2-hops.txt

### ISSUE THREAD

**Issue by michael20at** [JudyYe/zero-shot-gcn#4]
Sorry for reopening this again, but img-2-hops.txt is not included in the github repository (as far as I can see?), and the link you posted in the other issue requires authorization? How can I try the demo without those files?

**Comment by michael20at** [comment]
Ok, making progress now, downloaded img-3-hops.txt, tested it out on feature n01498406 (deleted everythin else), getting some results ['0.0', '0.0', '0.0', '0.9', '3.8'], but how to interpret them? How to get the corresponding labels printed or how can I look them up?

**Comment by JudyYe** [comment]
refer to #5 . Thanks.
