### ISSUE TITLE
Interpret results

### ISSUE THREAD

**Issue by michael20at** [JudyYe/zero-shot-gcn#5]
So sorry for opening another issue, but I'd really like this to work! Ok, making progress now, downloaded img-3-hops.txt, tested it out on feature n01498406 (deleted everythin else), getting some results ['0.0', '0.0', '0.0', '0.9', '3.8'], but how to interpret them? How to get the corresponding labels printed or how can I look them up?

How can I give it a picture and get a result in text form? (say cat or dog for example) Sorry if this questions sounds redundant, I'd really like to test this out. I've read the code pretty thoroughly, but no luck so far :-|

**Comment by JudyYe** [comment]
Yes. Sorry for replying late.

The number in the list corresponds to topk accuracy in [`top_retrv`](https://github.com/JudyYe/zero-shot-gcn/blob/master/src/test_imagenet.py#L85).
