### ISSUE TITLE
zero-shot learning的理解疑问？

### ISSUE THREAD

**Issue by TOT-BENCHMARK** [JudyYe/zero-shot-gcn#6]
通过zero-shot learning 只能判断一个测试的样本更像哪个训练的类，但是还是不知道他真正属于哪个类啊。能真正预测类别吗？

**Comment by xiaolonw** [comment]
zero-shot learning就是真正的预测类别，不是判断一个测试的样本更像哪个训练的类

**Comment by TOT-BENCHMARK** [comment]
看了一些资料大致了解了什么是zero-shot learning 。谢谢你的回复。
