### ISSUE TITLE
Did i need to get the imagenet original image

### ISSUE THREAD

**Issue by shenyingying** [JudyYe/zero-shot-gcn#9]
when i run the download_image.py, I got bug like this: 
http://www.image-net.org/download/synset?wnid=n01878061&username=liu1073133884&accesskey=imagenet&release=latest&src=stanford
!!! Error when downloading n01878061
http://www.image-net.org/download/synset?wnid=n03086457&username=liu1073133884&accesskey=imagenet&release=latest&src=stanford
!!! Error when downloading n03086457
http://www.image-net.org/download/synset?wnid=n04102285&username=liu1073133884&accesskey=imagenet&release=latest&src=stanford
!!! Error when downloading n04102285
http://www.image-net.org/download/synset?wnid=n13232779&username=liu1073133884&accesskey=imagenet&release=latest&src=stanford
!!! Error when downloading n13232779
http://www.image-net.org/download/synset?wnid=n02482060&username=liu1073133884&accesskey=imagenet&release=latest&src=stanford
!!! Error when downloading n02482060
http://www.image-net.org/download/synset?wnid=n07920222&username=liu1073133884&accesskey=imagenet&release=latest&src=stanford
!!! Error when downloading n07920222
http://www.image-net.org/download/synset?wnid=n02279637&username=liu1073133884&accesskey=imagenet&release=latest&src=stanford

i guess this because the permission of my account in imageNet but it's still when i try many times,can you help me ths!

**Comment by SJHBXShub** [comment]
Have you solved this problem?

**Comment by shenyingying** [comment]
ye, you should find a school email the log in imagenet

**Comment by zhujiagang** [comment]
@shenyingying Hi, I encounter the same problem. What do you mean by 'school email' and 'log in imagenet'. How to run the following command as you suggested?
`python tools/download_image.py --user $YOUR_USER_NAME --key $YOUR_ACCESS_KEY --save_dir ../images/ --hop 2 &`

**Comment by zhujiagang** [comment]
@shenyingying I've got it! You have to register and wait for a verification email. Then you have to agree some terms and user name and access key will be given.

**Comment by shenyingying** [comment]
sorry,i forget to reply your email,yeah,i also got it,but there is some confuse in my reading the code, what step you proceed in?can we interflow each other?发自我的华为手机-------- 原始邮件 --------主题：Re: [JudyYe/zero-shot-gcn] Did i need to get the imagenet original image (#9)发件人：zhujiagang 收件人：JudyYe/zero-shot-gcn 抄送：BlueSandals ,Mention @shenyingying I've got it! You have to register and wait for a verification email. Then you have to agree some terms and user name and access key will be given.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JudyYe/zero-shot-gcn","title":"JudyYe/zero-shot-gcn","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/JudyYe/zero-shot-gcn"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zhujiagang in #9: @shenyingying I've got it! You have to register and wait for a verification email. Then you have to agree some terms and user name and access key will be given."}],"action":{"name":"View Issue","url":"https://github.com/JudyYe/zero-shot-gcn/issues/9#issuecomment-419689545"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/JudyYe/zero-shot-gcn/issues/9#issuecomment-419689545",
"url": "https://github.com/JudyYe/zero-shot-gcn/issues/9#issuecomment-419689545",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [JudyYe/zero-shot-gcn] Did i need to get the imagenet original image (#9)",
"sections": [
{
"text": "",
"activityTitle": "**zhujiagang**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@zhujiagang",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"JudyYe/zero-shot-gcn\",\n\"issueId\": 9,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"JudyYe/zero-shot-gcn\",\n\"issueId\": 9\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/JudyYe/zero-shot-gcn/issues/9#issuecomment-419689545"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 371872884\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by zhujiagang** [comment]
@shenyingying Sure. But I've just downloaded the images yesterday and haven't started to read the codes. Is the size of downloaded images about 109G? My QQ number is 1058776021.

**Comment by shenyingying** [comment]
you qq need verify,my wechat is 17079600319,ths!发自我的华为手机-------- 原始邮件 --------主题：Re: [JudyYe/zero-shot-gcn] Did i need to get the imagenet original image (#9)发件人：zhujiagang 收件人：JudyYe/zero-shot-gcn 抄送：BlueSandals ,Mention @shenyingying Sure. But I've just downloaded the images yesterday and haven't started to read the codes. Is the size of downloaded images about 109G. My QQ number is 1058776021.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JudyYe/zero-shot-gcn","title":"JudyYe/zero-shot-gcn","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/JudyYe/zero-shot-gcn"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zhujiagang in #9: @shenyingying Sure. But I've just downloaded the images yesterday and haven't started to read the codes. Is the size of downloaded images about 109G. My QQ number is 1058776021."}],"action":{"name":"View Issue","url":"https://github.com/JudyYe/zero-shot-gcn/issues/9#issuecomment-419771694"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/JudyYe/zero-shot-gcn/issues/9#issuecomment-419771694",
"url": "https://github.com/JudyYe/zero-shot-gcn/issues/9#issuecomment-419771694",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [JudyYe/zero-shot-gcn] Did i need to get the imagenet original image (#9)",
"sections": [
{
"text": "",
"activityTitle": "**zhujiagang**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@zhujiagang",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"JudyYe/zero-shot-gcn\",\n\"issueId\": 9,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"JudyYe/zero-shot-gcn\",\n\"issueId\": 9\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/JudyYe/zero-shot-gcn/issues/9#issuecomment-419771694"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 371872884\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by zhangchuanyin** [comment]
> @shenyingying I've got it! You have to register and wait for a verification email. Then you have to agree some terms and user name and access key will be given.

how long can we receive the mail?

**Comment by JudyYe** [comment]
Relevant to #14
